LLNL/scr

- examples/test_api.c
- examples/test_common.c
In test_common.c:
- int and size_t was used for file sizes, thus it was impossible to have checkpoints larger than 2GB. Fixed.
- write_checkpoint returned the same value (0) both for success and error.
In test_api.c and test_common.c, more detailed error messages in case of errors.
> Fix types and error handling in examples

- README.md
This allows better in browser rendering by applications like GitHub and Atlassian Stash.
> Converted README to markdown

- README.md
- examples/Makefile.am
- examples/README.md
This change closes bitbucket issue 31.
> Added readme to examples, with build instructions

- src/scr.c
Free scr_halt_hash together with others.
> Fix minor memory leak

- m4/x_ac_pmix.m4
- src/scr_pmix_spawn.c
- testing/PMIX_TEST
- testing/scr_base.sh
- testing/submit_command.sh
updated PMIX and CPPR tests to reflect new changes
> CORCPPR-430: update SCR to reflect PMIx changes and fix build

- LICENSE.TXT
> Update license URL

- autogen.sh
- src/scr_byteswap.h
- src/scr_fetch.c
- src/scr_flush_sync.c
- src/scr_io.c
- src/scr_io.h
SCR now builds on a mac laptop 😀
> Apple port

- configure.ac
- examples/makefile.examples.in
- m4/x_ac_cppr.m4
- m4/x_ac_pmix.m4
- src/Makefile.am
- src/scr_flush_async_tlcc.c
Master now successfully builds! Fixes #31 and closes #29.
There are a number of real fixes needed, but these can be addressed later.
> Merge cleanup

- src/scr_globals.h
> fix exitcall PR

- scripts/TLCC/scr_list_down_nodes.in
- scripts/TLCC/scr_scavenge.in
- scripts/common/scr_hostlist.pm
- testing/BUILD_AND_RUN
- testing/TEST
Change pdsh to use exec module and related changes. Also some updates to testing scripts.
> make TLCC scripts work on Trinitite

- src/scr_fetch.c
- src/scr_flush.c
- src/scr_flush_async.c
- src/scr_flush_async_bbapi.c
- src/scr_flush_async_datawarp.c
- src/scr_flush_async_posix.c
- src/scr_param.c
- src/scr_pmix_spawn.c
- src/scr_reddesc_recover.c
a rank, he/him/his => it/it/its
the user, he/him/his => the user, they/them/their
> remove gender from comments

- doc/rst/_templates/layout.html
OMG this works. It fixes #118. You can view it here: http://scr.readthedocs.io/en/rst-toc/
> editing sidebar layout

- doc-dev/rst/developers/testing_bamboo.rst
- doc-dev/rst/developers/testing_new_systems.rst
- doc-dev/rst/index.rst
Documentation about the testing we are currently doing with SCR
> Dev test docs

- src/scr_param.c
- testing/TESTING.csh
This adds the new SCR_LOG parameters to the no app check.
> add new log params to no app check

- bootstrap.sh
It looks like I may have ran into link redirection issues.
Changing the links below allowed the bootstrap.sh to complete
> update github links

- src/CMakeLists.txt
- src/scr_index.c
- src/scr_rebuild_rs.c
This adds scavenge rebuild support for RS encoded datasets.
> add serial rebuild for reed-solomon

- src/scr.c
Check that SCR_PREFIX implied by environment variable / current working dir is consistent with SCR_PREFIX from config params.
> Configcheck

- .gitlab-ci.yml
Various tweaks and compiler flag fixes for Lassen builds, and updates to take care of recent changes to the develop branch.
> Fixes and updates to .gitlab-ci.yml

- src/scr_flush_async.c
Browsing the SCR async code, found some things to clean up.
> improve axl error handling when adding files

- doc/rst/users/api.rst
This merges the two different ``SCR_Config`` sections.  For clarity, it also separates ``Init/Finalize/Config`` into a new "startup" section and moves the "General API" to come after the "Restart API".
> doc: merge scr_config description

- README.md
- bootstrap.sh
- doc/rst/users/quick.rst
This PR updates the quick start guide for instructions for the components.
This will also update https://github.com/LLNL/scr/blob/quick/README.md
> doc: update quick start for components

- examples/run_test.sh
Reports exit code of test to ctest
> examples: report exit code of test to ctest

- doc/rst/users/build.rst
- doc/rst/users/quick.rst
- examples/makefile.examples.in
Resolves https://github.com/LLNL/scr/issues/301 and https://github.com/LLNL/scr/issues/302
> doc: update quick start cmake build of test_api

- scripts/SLURM/scr_get_jobstep_id.in
- scripts/SLURM/scr_run.in
- scripts/common/scr_watchdog.in
- src/scr_flush_file.c
Cleans up watchdog scripts, mostly adding error checks and code to handle special cases (eg watchdog frequency high enough / code stuck early enough that the watchdog is called before there is any output).
A bugfix to handle change `squeue` output (leading spaces).
No actual functional change.
> watchdog updates

- scripts/test/test_scr_hostlist.in
The script to test some scr_hostlist functions.  This is an .in file as it needs to know the include path for scr_hostlist.pm, so we'll have to configure it via CMake.  Also, I haven't had a chance to look at how we add it as a proper test in CMake either.  Open to suggestions.
> unit tests for scr_hostlist.pm
