- src/scr_retries_halt.c
Previously it was looking for a halt file in $PREFIX/halt.scr. But the
file is located in $PREFIX/.scr/halt.scr
> fix: Look for a halt file in the right place in scr_retries_halt

- scripts/cray_xt/scr_halt.in
- scripts/cray_xt/scr_list_down_nodes.in
Some cray_xt scripts were never fully updated with the rename from scr_cntl_dir to scr_list_dir.
> Clean up detritus of scr_cntl_dir to scr_list_dir rename

- testing/TEST
As of commit bc040fe a halt file with SCR_FINALIZE as a halt condition no longer prevents a new job from running. This fixes #13.
This PR removes tests for the previous behavior from testing/TEST
> Removed test for halt behavior that changed

- src/scr.c
- src/scr.h
- src/scr_conf.h
- src/scr_globals.c
- src/scr_halt.c
Some apps like to print summary info before exit, so calling exit() from within SCR is not acceptable.  This adds a new query functions so an app can ask SCR if it should exit.  It also provides a parameter so apps can configure SCR to not auto-exit.
> add exit query and param to disable auto-exit on active halt condition

- src/scr.c
If any process reports valid=0 in Complete_restart, then the app failed to read its checkpoint.  For now, let's abort.  A better failure mode would be to drop this from cache, mark it as invalid in the index file so we don't fetch it again, fetch the next most recent restart, and have the caller cycle through the restart calls again.  We can implement the more graceful failure if we have time for v1.2, but at least we have something with this.
> check valid flag in SCR_Complete_restart and bail if invalid

- testing/TEST
Previously we had to change the node specifying logic between sites.
This should be site-agnostic for SLURM nodelists.
> update test finding downnodes

- testing/TEST
Have scr_list_down_nodes report reasons when it should not fail anyway.
This may help with debugging bamboo failures.
> Have downnodes report reasons

- scripts/LSF/scr_list_down_nodes.in
- scripts/PMIX/scr_list_down_nodes.in
- scripts/TLCC/scr_list_down_nodes.in
- scripts/cray_xt/scr_list_down_nodes.in
ping warnings were leading to incorrect assumptions about whether ping had succeeded. Since we never check ping output (only error code) decided to suppress warnings by redirecting stderr to stdout.
> Redirect ping stderr to stdout

- scripts/LSF/scr_list_down_nodes.in
- scripts/LSF/scr_scavenge.in
- scripts/PMIX/scr_list_down_nodes.in
- scripts/PMIX/scr_scavenge.in
- scripts/TLCC/scr_list_down_nodes.in
- scripts/TLCC/scr_scavenge.in
- scripts/common/scr_hostlist.pm
- scripts/cray_xt/scr_list_down_nodes.in
- scripts/cray_xt/scr_scavenge.in
At LLNL, nodes typically follow a syntax like <name><number> which can be read using a regex like \w+\d+.  For example, node 34 on a system called "machine" would be "machine34".  This enables a list of machines to be given in simple compressed format like: machine34,machine35,machine36,machine37 --> machine[34-37].
Other sites use different conventions in node names, including a suffix following the numbers or perhaps dashes/dots and multiple numbers.  This change extends the node name range to have an arbitrary prefix and suffix.  It also drops the logic that compresses a list of nodes, since that becomes non-trivial in other formats.  For example, this supports ranges like:
"machine2-[3-5]-vm1" --> "machine2-3-vm1,machine2-4-vm1,machine2-5-vm1"
> Generalize node name format

- testing/TESTING.csh
These files are useful when testing by hand.  Drop the lines about building with configure, switched to cmake.
> drop configure in TESTING.csh instructions

- src/scr.c
A fix for #125.
This makes SCR_Route_file **always** successful by returning a copy of the original filename.
> Always Route File

- examples/test_api.c
test_api.c was calling sprintf with the wrong arguments.  I am pretty sure it should have been printf.
> Fix warning/bad behavior in example

- cmake/FindBBAPI.cmake
- src/scr_flush_async_bbapi.c
When building SCR with the `-DSCR_ASYNC_API=IBM_BBAPI` option, the build errors out with:
```
libscr.so: undefined reference to `scr_bool_is_flushing'
libscr.so: undefined reference to `scr_bool_need_flush'
libscr.so: undefined reference to `getLastErrorDetails'
```
This updates the out-of-date SCR function names that get called when using BBAPI, as well as updating the call to BBAPI's `BB_GetLastErrorDetails()`.
Also adds hints for where the BBAPI Libraries might be found to avoid needing to provide the `-DWITH_BBAPI_PREFIX` cmake option (as was done in AXL).
> Fix compile error when building with BBAPI

- README.md
- bootstrap.sh
- Add an easy-bake bootstrap.sh script to download and build all SCR's dependencies.
> Add bootstrap.sh

- src/scr_fetch.c
- src/scr_flush_async.c
- src/scr_flush_sync.c
`Filo_Fetch()`/`Filo_Flush()` were recently updated to allow you to specify the AXL transfer type.  Use the 'pthread' transfer type for good performance across all types of filesystems.
**Note: this requires https://github.com/ECP-VeloC/filo/pull/6 to be in first.  Do not merge this PR until it's in.**
> Update Filo_Fetch()/Filo_Flush() calls

- examples/test_api.c
Simple bug fix. Return value was not saved before being used, which was fine under normal conditions since the unset value of scr_retval happened to be SCR_SUCCESS, but a problem if SCR_Start_restart() actually failed.
> Return value used without being saved from SCR_Start_restart()

- doc-dev/rst/developers/store_descriptors.rst
- src/scr.c
- src/scr_fetch.c
- src/scr_flush_async.c
- src/scr_flush_sync.c
- src/scr_storedesc.c
- src/scr_storedesc.h
Update the TYPE definition in the STORE descriptors to allow you to specify which AXL transfer type SCR should use to copy files into the STORE.  For example:
```
STORE=/tmp          GROUP=NODE   COUNT=1
STORE=/ssd          GROUP=NODE   COUNT=3  TYPE=bbapi
STORE=/dev/persist  GROUP=NODE   COUNT=1  ENABLED=1  MKDIR=0
STORE=/p/lscratcha  GROUP=WORLD  TYPE=pthread
```
The old TYPE definitions (like "DATAWARP" and "POSIX") are mapped to the AXL types for backwards compatibility.
> Specify custom STORE transfer type in scr.conf

- doc/rst/users/api.rst
- doc/rst/users/integration.rst
- examples/test_api.c
- src/scr.c
- src/scr_flush.c
- src/scr_index_api.c
- src/scr_index_api.h
If some process marks a restart as invalid, it would be nice to load up the next most recent checkpoint and loop until we find one that works.  The idea is support something like:
```
int have_restart = 0;
int restarted = 0;
do {
scr_have_restart(&have_restart)
if (have_restart) {
scr_start_restart()
scr_route_file()
rc = scr_complete_restart(valid)
restarted = (rc == SCR_SUCCESS)
}
} while (have_restart && !restarted);
```
This PR is currently noisy because it's based on https://github.com/LLNL/scr/pull/166
> Restartloop

- doc/rst/users/build.rst
- doc/rst/users/quick.rst
Add instructions for installing the dependencies for SCR on Fedora.  This should install all the required packages except pdsh.
```
sudo dnf groupinstall "Development Tools"
sudo dnf install cmake gcc-c++ mpi mpi-devel environment-modules zlib-devel
[restart shell]
module load mpi
```
> Add RPM dependencies for Fedora 32 in docs

- src/scr.c
- src/scr_cache_rebuild.c
- src/scr_conf.h
- src/scr_fetch.c
- src/scr_fetch.h
- src/scr_flush.c
- src/scr_globals.c
- src/scr_globals.h
- src/scr_index.c
- src/scr_index_api.c
- src/scr_index_api.h
- src/scr_io.c
- src/scr_keys.h
- src/scr_reddesc.c
While testing the restart loop and forcing checkpoints to be bad so that SCR would fetch the next most recent checkpoint, I came across an old bug in our index metadata.  This file resides in the prefix directory to record the list of datasets on the parallel file system.  In short, it was possible and somewhat typical to end up with multiple and inconsistent entries in the index for a given dataset id value.
This was a desired feature when SCR was creating the dataset directories on the parallel file system.  One could flush multiple copies of the same checkpoint, where each lived in its own directory.  Then if one copy of a particular checkpoint was corrupted, one could try another copy of the same checkpoint if available before falling back to try an older checkpoint.
However, now that …
> enforce one-to-one mapping of id-to-name

- src/scr.c
- src/scr_cache_index.c
- src/scr_cache_index.h
- src/scr_cache_rebuild.c
- src/scr_fetch.c
- src/scr_globals.c
- src/scr_globals.h
This defines a new SCR_CURRENT configuration parameter that can be used to name the checkpoint SCR should restart from.  If set, it sets the "current" maker within the index file under the prefix directory, overwriting any existing setting that might already be there.  This is most typically used to restart from a checkpoint that is older than the most recent available.
This provides an alternative to having to execute the ```scr_index --current <name>``` command before starting the job.  One can now set SCR_CURRENT as an environment variable or in a config file and soon through ```SCR_Config()```.
Given that this might be set in a config file or implied in the application command line throughout the duration of a job, we need to be careful to only process this once within the job …
> add SCR_CURRENT

- src/CMakeLists.txt
- src/scr_print.c
This adds an ```scr_print``` binary, which is essentially a duplicate of the ```kvtree_print``` right now.  This separate binary abstracts the fact from users that SCR files are really stored as kvtree files.
> add scr_print binary

- scripts/LSF/scr_jsrun.in
- scripts/LSF/scr_list_down_nodes.in
- scripts/LSF/scr_lrun.in
- scripts/LSF/scr_mpirun.in
- scripts/LSF/scr_run.in
- scripts/LSF/scr_scavenge.in
- scripts/PMIX/scr_list_down_nodes.in
- scripts/PMIX/scr_run.in
- scripts/PMIX/scr_scavenge.in
- scripts/TLCC/scr_list_down_nodes.in
- scripts/TLCC/scr_run.in
- scripts/TLCC/scr_scavenge.in
- scripts/cray_xt/scr_list_down_nodes.in
- scripts/cray_xt/scr_run.in
- scripts/cray_xt/scr_scavenge.in
- src/scr.c
- src/scr_cache_rebuild.c
- src/scr_conf.h
- src/scr_copy.c
- src/scr_fetch.c
- src/scr_flush_async.c
- src/scr_flush_sync.c
- src/scr_globals.c
- src/scr_globals.h
- src/scr_log.c
- src/scr_log.h
- src/scr_log_event.c
- src/scr_log_transfer.c
- src/scr_reddesc.c
- src/scr_reddesc.h
This adds a simple text file as a log option, enabled with ```SCR_LOG_TXT_ENABLE=1```.  The text file will live in the hidden .scr directory of the job's prefix directory.  Records are appended one line at a time.  Example output:
```
>>: cat $SCR_PREFIX/.scr/log
2020-05-26T23:19:40: host=quartz28, jobid=5275576, event="START"
2020-05-26T23:19:40: host=quartz28, jobid=5275576, event="COMPUTE STARTED", note="(null)", dset=1, secs=0.000000
2020-05-26T23:19:40: host=quartz28, jobid=5275576, event="COMPUTE COMPLETED", note="(null)", dset=1, secs=0.002699
2020-05-26T23:19:40: host=quartz28, jobid=5275576, event="CHECKPOINT STARTED", note="/dev/shm", dset=1, secs=0.000000
2020-05-26T23:19:40: host=quartz28, jobid=5275576, event="CHECKPOINT COMPLETED", note="/dev/shm", dset=1, secs=0.029750 …
```
> add simple text file and syslog as log options

- src/scr.c
- src/scr.h
- src/scr_dataset.h
- src/scr_index.c
- src/scr_index_api.c
- src/scr_index_api.h
- src/scrf.c
This defines a new ```SCR_Current(const char* name)``` API that an application can use to specify the current checkpoint in the index file.  This also updates the internal SCR counters to match the id values for that checkpoint.  This latter functionality is needed so that SCR can set its counters appropriately in the event that the application has restarted without using the SCR restart API.  In that case, this gives the application a way to inform SCR about which checkpoint it loaded.  It might make sense to split this functionality into two separate API calls, but that is left for future work.
The call to ```SCR_Current``` does the following, assuming that the named dataset actually exists in the index file:
- update the index file to set the named dataset to be current
- change SCR's …
> add scr_current api

- examples/test_config.c
- src/scr.c
- src/scr_config.c
- src/scr_config.h
- src/scr_config_mpi.c
- src/scr_config_serial.c
- src/scr_globals.h
- src/scr_log.c
- src/scr_param.c
- src/scr_param.h
This updates SCR_Config in a few ways:
- add state transition check that user calls SCR_Config before calling SCR_Init
- add check that user calls SCR_Config with all processes
- add check that input string is the same across all ranks
- call scr_param_init/scr_param_finalize internally so that various hashes are defined (fixes a bug when calling SCR_Config after user has set parameter through environment variable)
- return NULL when setting a value.  This is because we now have to strdup the returned string which then needs to be freed by the caller, and this just adds extra work for most cases when settings values.  Instead, if the caller wants to know the value, they can check the value with a subsequent call to SCR_Config to query the setting.
Updates scr_param_init to create app hash …
> fix scr_config when user sets param through environment

- src/scr.c
- src/scr_globals.c
- src/scr_globals.h
This defines a new ```SCR_CACHE_PURGE``` parameter to ask SCR to purge all datasets from cache during ```SCR_Init```.  It does this without flushing those datasets to the file system.
This setting is helpful when developing and testing SCR within an application.  Without this, one has to manually clean the cache between runs within a compute node allocation using commands like:
```
srun -n $nodes -N $nodes rm -rf /dev/shm/${USER}/scr.{$SLURM_JOBID}
srun -n $nodes -N $nodes rm -rf /ssd/${USER}/scr.{$SLURM_JOBID}
```
This setting does not delete the cache directory or other SCR metadata in cache.
Resolves https://github.com/LLNL/scr/issues/219
> define parameter to purge cache on restart

- src/scr_cache.c
- src/scr_meta.c
- src/scr_meta.h
When looking for changes to a file before deleting it from cache, this replaces the ctime check with checks against mode bits, uid, and gid instead.  The ctime check was intended as a quick way to look for changes to those fields.  However, a rebuild of a file would change ctime, which led to false positives.
> check mode bits, uid, and gid instead of ctime for file changes

- doc/rst/users/manage.rst
- examples/test_api.c
- scripts/common/scr_postrun.in
- src/scr_index.c
Picks up changes to scr_index output which started here https://github.com/LLNL/scr/pull/176
After discussions with some users, having a way to expose the DSET id could be helpful.  Adding it back for now.
Current output looks like:
```
DSET VALID FLUSHED             CUR NAME
6 YES   2020-06-27T15:05:36   * ckpt.6
5 YES   2020-06-27T15:05:36     ckpt.5
```
TODO: We should probably list which items are checkpoints vs pure output in some field.  It might also be handy to show size and number of files (to encourage people to delete stuff).
> scr_index: define --add option to insert dataset into index

- src/scr.c
- src/scr.h
SCR_Config is working well in the apps so far, but it does lead to a lot of patterns like the following:
```
char config[1024];
snprintf(config, sizeof(config), "SCR_FLUSH=%d", checkpoint_freq);
SCR_Config(config);
```
This adds a formatted option, so the above simplifies to:
```
SCR_Configf("SCR_FLUSH=%d", checkpoint_freq);
```
This should help with C/C++ users.  Don't know if there is something similar for Fortran or not.
> add scr_configf for formatted config calls

- doc/rst/users/api.rst
- doc/rst/users/config.rst
- doc/rst/users/halt.rst
- src/scr.c
- src/scr_conf.h
- src/scr_globals.c
- src/scr_globals.h
By default, SCR calls ``exit(0)`` when it detects an active halt condition.
https://github.com/LLNL/scr/blob/073d0352b06bbaf3034f411f2b882902cd74f80e/src/scr.c#L369
This check executes during ``SCR_Init`` and during ``SCR_Complete_output`` after completing a successful checkpoint.  This behavior is useful for some apps, but others will likely find this behavior to be disruptive.
Since the docs have been updated to suggest that apps make calls to ``SCR_Should_exit``, this switches the default SCR behavior to *not* exit.
Users can restore the old behavior by setting ``SCR_HALT_EXIT=1``.
Changed documentation in places to match this new default behavior:
- https://scr.readthedocs.io/en/v2.0.0/users/api.html#scr-complete-checkpoint
- …
> change default behavior to not exit on active halt condition

- doc/rst/users/config.rst
- src/scr.c
- src/scr_globals.c
- src/scr_globals.h
- src/scr_index_api.c
- src/scr_index_api.h
- src/scr_prefix.c
- src/scr_prefix.h
Some applications provide an option to let their users restart the run from scratch.  This parameter tells SCR to delete all datasets from the prefix directory during SCR_Init.  It deletes all datasets (both checkpoint and output) listed in the index file.
> add SCR_PREFIX_PURGE to delete all datasets listed in index file

- src/scr_cache.c
The cache purge function would delete the cache index file, but it did not clear the object.  If a run then later rewrote the cache index file, any settings in the object (which might now be stale) would be written back to the file so that a subsequent run would pick up those inconsistent settings.
> fix: clear cache index object in cache purge

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Ping @kathrynmohror @adammoody 
Adding code of conduct and contributing guide for SCR. Something similar will go into the components. 
@kathrynmohror, I put your email down as the Code of conduct contact person (and project PI), since I didn't feel that those emails should go to the mailing list. Is this okay? I could also leave out that portion.
> add code of conduct and contributing guide

- scripts/TLCC/scr_run.in
scr can use use libyogrt to find out how much time is left in a job. However libyogrt is an optional dependency and scr can be built without it. 
For many scheduling systems scr_run sets an env variable `SCR_END_TIME` which is used as a fallback to compute the remaining time.
This pull request sets this variable based on information obtained from `scrontrol`.
Tested to work on SLURM on my workstation.
> set SCR_END_TIME for SLURM to be used when YOGRT is not present

- .gitignore
Our .gitignore file listed lots of generated files from autotools.  This is no longer needed now that we're building with cmake.  However, those lines interfere with checking a full snapshot of the scr source into other git projects.
> remove autotools artifacts from gitignore

- scripts/common/scr_param.pm.in
- src/scr_param.c
- src/scr_reddesc.c
Some people would like to run test jobs in which they get an allocation and then run multiple, independent job steps, where each job step is actually a different test/simulation.  Additionally, these tests may run on the same node.  This leads to a problem because SCR uses the same control and cache directory for all of those, e.g., ``/dev/shm/$USER/scr.$SLURM_JOBID``, whereas they each need their own directory.
This is unusual, but a work around would be to let the user specify different ``SCR_CNTL_BASE`` and ``SCR_CACHE_BASE`` directories for each of their tests.  However, SCR restricts someone from setting ``SCR_CNTL_BASE`` at run time.  It is a configure option or it must be set in the "system" config file, which is installed to a path that is hard coded at build time.
This constraint …
> allow user to set SCR_CNTL_BASE at runtime

- src/scr_flush_async.c
- src/scr_flush_sync.c
When using ``SCR_GLOBAL_RESTART=1``, we flush checkpoints on restart.  However, this would not work if the user had also set ``SCR_FLUSH=0``.  This allows one to use flush on restart without having SCR flush any other checkpoints during the run.
> fix: for global restart, enable flush_sync when scr_flush is disabled

- doc/rst/users/build.rst
- doc/rst/users/config.rst
- doc/rst/users/overview.rst
Update documentation to remove restriction on the user setting SCR_CNTL_BASE at run time.
> doc: update text about setting SCR_CNTL_BASE

- src/scr_index.c
@tonyhutter , we whacked a couple lines needed for scavenge as part of the -Wall commit:
https://github.com/LLNL/scr/commit/5195a7243fec6da0bb22ee885b459958ba81cf63
Was there a reason for this or just a mistake?
> fix: restore list of files in scr_index --build

- testing/TESTING.csh
- testing/TESTING.sh
- switch to use dependencies installed by bootstrap.sh
- add salloc to allocate pdebug nodes
- drop old lines that are no longer relevant
> test: use deps installed by bootstrap

- testing/TESTING.csh
- testing/TESTING.sh
Commenting out this test rather than deleting it in the hopes that we might bring it back soon.  This is useful as a reminder of what the functionality could support.
> comment out CRC check in TESTING scripts

- examples/CMakeLists.txt
Someone recently reported a problem with the interpose examples when running the CMake tests.  Since we no longer build the SCR interposition library, these examples and tests are deprecated.  This removes them from the build and list of tests to resolve the CMake test problem.
I've left the actual test source files, because we may bring the interposition library back at some point.
> examples: drop interpose programs and tests

- examples/makefile.examples.in
This works in my testing.
The examples and this functional makefile is installed to `install-path/scr/share/examples/`. Users can run `make` there to successfully build all the examples.
The only thing to note is that if ENABLE_FORTRAN is turned of at the SCR project level, the examples will still include the fortran examples. If fortran is disabled because it’s not installed (such as mpif90 does not exist) then there may be an error.
> clean up of examples makefile

- doc/rst/users/integration.rst
- doc/rst/users/quick.rst
I've fixed up the build and link documentation for both CMake and Spack paths.
Closes #301. Closes #302. Closes #303. Closes #304.
> Spack and CMake review of build docs

- bootstrap.sh
This updates bootstrap.sh to build the dependencies optimized by default.  It also checks out specific tags corresponding to versions for SCR-v3.0rc1.
One can pass a ``--debug`` flag to build Veloc dependencies in ``Debug`` mode, rather than ``Release``.
One can pass a ``--dev`` flag to keep the latest version of each VeloC dependency, rather than checking out a tag.
> bootstrap: add --dev and --debug

- examples/test_config.c
- src/scr.c
This addresses our failing test case: https://github.com/LLNL/scr/issues/313.
This happens in a situation like the following:
```
SCR_Config("STORE=/dev/shm     GROUP=NODE COUNT=1")
SCR_Config("STORE=/dev/shm/foo GROUP=NODE COUNT=1")
char* value = SCR_Config("STORE")
```
The return value in the query above is not well defined since STORE has two different settings at this point.
This modifies SCR_Config to print and error and return NULL when querying a key with multiple values.
> fix: drop an SCR_Config test reading STORE value

- doc/rst/users/api.rst
- src/scr.c
Permit users to call SCR_Config after SCR_Init to query a parameter.  Continue to throw an error if users try to change/unset a parameter after SCR_Init.
> fix: allow scr_config queries after init

- src/scr.c
- src/scr_flush_async.c
- src/scr_flush_async.h
- src/scr_flush_sync.c
- src/scr_globals.c
- src/scr_globals.h
- src/scr_storedesc.c
Currently, SCR only permits a single outstanding async flush at a time.  If the job attempts to start a second, SCR blocks the job and waits on the first to finish.  This extends SCR to support an arbitrary number of simultaneous async flush operations.
> allow for multiple outstanding flush operations
